# Generated by Django 4.2.5 on 2023-09-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[("O'quvchi", 'Oquvchi'), ("O'qituvchi", 'Oqituvchi')], default="O'quvchi", max_length=155),
        ),
    ]
